# Generated by Django 6.1 on 2026-09-14 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100)),
                ('farm_name', models.CharField(max_length=150)),
                ('farm_type', models.CharField(choices=[('FISHPOND', 'Fishpond'), ('FISH_CAGE', 'Fish Cage'), ('FISH_PEN', 'Fish Pen'), ('OTHER', 'Other')], max_length=20)),
                ('area', models.DecimalField(decimal_places=2, help_text='Farm area in hectares', max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farmers.farmer')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='farmers.municipality')),
            ],
            options={
                'ordering': ['municipality', 'barangay', 'farm_name'],
            },
        ),
    ]
